apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-minion.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-minion.name" . }}
    helm.sh/chart: {{ include "kafka-minion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-minion.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
      labels:
        app.kubernetes.io/name: {{ include "kafka-minion.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TELEMETRY_HOST
              value: {{ .Values.telemetry.host | quote }}
            - name: TELEMETRY_PORT
              value: {{ .Values.telemetry.port | quote }}
            - name: EXPORTER_IGNORE_SYSTEM_TOPICS
              value: {{ .Values.exporter.metricsPrefix | quote }}
            - name: EXPORTER_METRICS_PREFIX
              value: {{ .Values.exporter.metricsPrefix | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: KAFKA_BROKERS
              value: {{ required "A valid entry for kafka.brokers is required" .Values.kafka.brokers | quote }}
            - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
              value: {{ .Values.kafka.consumerOffsetsTopic | quote }}
            {{- if .Values.kafka.sasl.enabled }}
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ template "kafka-minion.saslSecret" . }}"
                  key: username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "kafka-minion.saslSecret" . }}"
                  key: password
            - name: KAFKA_SASL_USE_HANDSHAKE
              value: {{ .Values.kafka.sasl.useHandshake | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
