{{- if and (.Values.kafka.sasl.enabled) (not .Values.kafka.sasl.existingCredentialsSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "kafka-minion.name" . }}
    chart: {{ include "kafka-minion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "kafka-minion.saslSecret" . }}
type: Opaque
data:
  username: {{ .Values.kafka.sasl.username | b64enc }}
  password: {{ .Values.kafka.sasl.password | b64enc }}
{{- end -}}